services:
  f1-undercut-web:
    image: ghcr.io/PavDev3/f1-undercut-web:latest
    container_name: f1-undercut-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8085:80"
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup f1-undercut-web